language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=django==1.5.1
  - DJANGO=django==1.4.5

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.5

install:
  - pip install $DJANGO times
  - python setup.py install

script: make test
services: redis
