language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.9.7
  - DJANGO=1.8.13

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.9.7

install:
  - pip install Django==$DJANGO times
  - python setup.py install

script: make test
services: redis
