language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=1.8.0
  - DJANGO=1.7.7
  - DJANGO=1.6.11
  - DJANGO=1.5.12
  - DJANGO=1.4.20

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.20
    - python: "2.6"
      env: DJANGO=1.7.7
    - python: "2.6"
      env: DJANGO=1.8.0

install:
  - pip install Django==$DJANGO times
  - python setup.py install

script: make test
services: redis
