language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.9.9
  - DJANGO=1.8.18
  - DJANGO=1.10.8
  - DJANGO=1.11.7

install:
  - pip install Django==$DJANGO times
  - python setup.py install

script: make test
services: redis
